pipeline {
    agent any
    
    stages {
        stage('Get Source Code') {
            steps {
                git 'https://github.com/ZrmindzG/TestingFramework.git'
                echo "Hello, World!"
            }
        }
        stage('Build Code') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('Run Test') {
            steps {
                bat 'mvn compile'
            }
        }
    }
}
